apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo-1
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest-not-avaialable