apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: get-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: Pod
metadata:
  name: kanister-pod
spec:
  containers:
    - name: kanister
      image: kanisterio/kanister-kubectl:1.18