apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container-1
      image: busybox:latest
      command: ['ping', '8.8.8.8']
      volumeMounts:
      - mountPath: /cache
        name: cache-volume
    - name: test-container-2
      image: busybox:latest
      command: ['ping', '8.8.8.8']
      volumeMounts:
      - mountPath: /cache
        name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}