apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-example
stringData:
  password: abvxwt11
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox:latest
      command: ['ping', '8.8.8.8']
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: password