apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxapp
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxapp
        image: nginx:not-available