apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
    - name: create-static-file
      image: alpine
      command: ["touch","/tmp/static_file"]
      volumeMounts:
        - mountPath: /tmp
          name: my-data
  containers:
    - name: alpine
      image: alpine
      args:
      - bin/sh
      - -c
      - touch /tmp/static_file; sleep 30; rm -rf /tmp/static_file; sleep 600
      volumeMounts:
        - mountPath: /tmp
          name: my-data
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/static_file
        initialDelaySeconds: 5
        periodSeconds: 1
  volumes:
    - name: my-data
      emptyDir: {}